import { createContext, useContext, useState } from 'react'

const translations = {
  fr: {
    dashboard: 'Tableau de bord',
    missions: 'Missions',
    volunteers: 'Bénévoles',
    beneficiaries: 'Bénéficiaires',
    donations: 'Donations',
    convoys: 'Convois',
    events: 'Événements',
    reports: 'Rapports',
    notifications: 'Notifications',
    settings: 'Paramètres',
    login: 'Connexion',
    register: "S'inscrire",
    logout: 'Déconnexion',
    email: 'Email',
    password: 'Mot de passe',
    firstName: 'Prénom',
    lastName: 'Nom',
    phone: 'Téléphone',
    address: 'Adresse',
    city: 'Ville',
    region: 'Région',
    search: 'Rechercher',
    add: 'Ajouter',
    edit: 'Modifier',
    delete: 'Supprimer',
    save: 'Enregistrer',
    cancel: 'Annuler',
    confirm: 'Confirmer',
    status: 'Statut',
    priority: 'Priorité',
    actions: 'Actions',
    total: 'Total',
    active: 'Actif',
    completed: 'Terminé',
    planned: 'Planifié',
    cancelled: 'Annulé',
    title: 'Titre',
    description: 'Description',
    startDate: 'Date de début',
    endDate: 'Date de fin',
    budget: 'Budget',
    amount: 'Montant',
    donor: 'Donateur',
    noData: 'Aucune donnée disponible',
    loading: 'Chargement...',
    welcome: 'Bienvenue',
    totalMissions: 'Total Missions',
    activeMissions: 'Missions Actives',
    totalVolunteers: 'Total Bénévoles',
    totalBeneficiaries: 'Total Bénéficiaires',
    totalDonations: 'Total Donations',
    totalEvents: 'Total Événements',
    totalConvoys: 'Total Convois',
    monthlyDonations: 'Donations Mensuelles',
    missionsByStatus: 'Missions par Statut',
    regionalDistribution: 'Distribution Régionale',
    recentDonations: 'Donations Récentes',
    platformTitle: 'Plateforme Humanitaire Maroc',
    heroTitle: 'Ensemble pour un Maroc Solidaire',
    heroSubtitle: 'Plateforme intelligente de gestion des missions humanitaires et des bénévoles au Maroc',
    getStarted: 'Commencer',
    learnMore: 'En savoir plus',
    forgotPassword: 'Mot de passe oublié ?',
    rememberMe: 'Se souvenir de moi',
    donationAmount: 'Montant du don',
    paymentMethod: 'Méthode de paiement',
    skills: 'Compétences',
    available: 'Disponible',
    unavailable: 'Indisponible',
    familySize: 'Taille de la famille',
    emergencyLevel: "Niveau d'urgence",
    departureCity: 'Ville de départ',
    destinationCity: 'Ville de destination',
    cargo: 'Cargaison',
    low: 'Faible',
    medium: 'Moyen',
    high: 'Élevé',
    critical: 'Critique',
    pending: 'En attente',
    inTransit: 'En transit',
    delivered: 'Livré',
    delayed: 'Retardé',
    upcoming: 'À venir',
    ongoing: 'En cours',
    allRegions: 'Toutes les régions',
    allStatuses: 'Tous les statuts',
    filterByRegion: 'Filtrer par région',
    filterByStatus: 'Filtrer par statut',
    exportPdf: 'Exporter PDF',
    details: 'Détails',
    assignVolunteers: 'Affecter des bénévoles',
    close: 'Fermer'
  },
  ar: {
    dashboard: 'لوحة التحكم',
    missions: 'المهمات',
    volunteers: 'المتطوعون',
    beneficiaries: 'المستفيدون',
    donations: 'التبرعات',
    convoys: 'القوافل',
    events: 'الأحداث',
    reports: 'التقارير',
    notifications: 'الإشعارات',
    settings: 'الإعدادات',
    login: 'تسجيل الدخول',
    register: 'إنشاء حساب',
    logout: 'تسجيل الخروج',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    firstName: 'الاسم الأول',
    lastName: 'اللقب',
    phone: 'الهاتف',
    address: 'العنوان',
    city: 'المدينة',
    region: 'الجهة',
    search: 'بحث',
    add: 'إضافة',
    edit: 'تعديل',
    delete: 'حذف',
    save: 'حفظ',
    cancel: 'إلغاء',
    confirm: 'تأكيد',
    status: 'الحالة',
    priority: 'الأولوية',
    actions: 'الإجراءات',
    total: 'المجموع',
    active: 'نشط',
    completed: 'مكتمل',
    planned: 'مخطط',
    cancelled: 'ملغى',
    title: 'العنوان',
    description: 'الوصف',
    startDate: 'تاريخ البدء',
    endDate: 'تاريخ الانتهاء',
    budget: 'الميزانية',
    amount: 'المبلغ',
    donor: 'المتبرع',
    noData: 'لا توجد بيانات',
    loading: 'جاري التحميل...',
    welcome: 'مرحباً',
    totalMissions: 'إجمالي المهمات',
    activeMissions: 'المهمات النشطة',
    totalVolunteers: 'إجمالي المتطوعين',
    totalBeneficiaries: 'إجمالي المستفيدين',
    totalDonations: 'إجمالي التبرعات',
    totalEvents: 'إجمالي الأحداث',
    totalConvoys: 'إجمالي القوافل',
    monthlyDonations: 'التبرعات الشهرية',
    missionsByStatus: 'المهمات حسب الحالة',
    regionalDistribution: 'التوزيع الجهوي',
    recentDonations: 'التبرعات الأخيرة',
    platformTitle: 'المنصة الإنسانية المغرب',
    heroTitle: 'معاً من أجل مغرب متضامن',
    heroSubtitle: 'منصة ذكية لإدارة المهمات الإنسانية والمتطوعين في المغرب',
    getStarted: 'ابدأ الآن',
    learnMore: 'اعرف المزيد',
    forgotPassword: 'نسيت كلمة المرور؟',
    rememberMe: 'تذكرني',
    donationAmount: 'مبلغ التبرع',
    paymentMethod: 'طريقة الدفع',
    skills: 'المهارات',
    available: 'متاح',
    unavailable: 'غير متاح',
    familySize: 'حجم الأسرة',
    emergencyLevel: 'مستوى الطوارئ',
    departureCity: 'مدينة المغادرة',
    destinationCity: 'مدينة الوصول',
    cargo: 'الشحنة',
    low: 'منخفض',
    medium: 'متوسط',
    high: 'مرتفع',
    critical: 'حرج',
    pending: 'قيد الانتظار',
    inTransit: 'في الطريق',
    delivered: 'تم التسليم',
    delayed: 'متأخر',
    upcoming: 'قادم',
    ongoing: 'جاري',
    allRegions: 'كل الجهات',
    allStatuses: 'كل الحالات',
    filterByRegion: 'تصفية حسب الجهة',
    filterByStatus: 'تصفية حسب الحالة',
    exportPdf: 'تصدير PDF',
    details: 'التفاصيل',
    assignVolunteers: 'تعيين المتطوعين',
    close: 'إغلاق'
  },
  en: {
    dashboard: 'Dashboard',
    missions: 'Missions',
    volunteers: 'Volunteers',
    beneficiaries: 'Beneficiaries',
    donations: 'Donations',
    convoys: 'Convoys',
    events: 'Events',
    reports: 'Reports',
    notifications: 'Notifications',
    settings: 'Settings',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    email: 'Email',
    password: 'Password',
    firstName: 'First Name',
    lastName: 'Last Name',
    phone: 'Phone',
    address: 'Address',
    city: 'City',
    region: 'Region',
    search: 'Search',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    status: 'Status',
    priority: 'Priority',
    actions: 'Actions',
    total: 'Total',
    active: 'Active',
    completed: 'Completed',
    planned: 'Planned',
    cancelled: 'Cancelled',
    title: 'Title',
    description: 'Description',
    startDate: 'Start Date',
    endDate: 'End Date',
    budget: 'Budget',
    amount: 'Amount',
    donor: 'Donor',
    noData: 'No data available',
    loading: 'Loading...',
    welcome: 'Welcome',
    totalMissions: 'Total Missions',
    activeMissions: 'Active Missions',
    totalVolunteers: 'Total Volunteers',
    totalBeneficiaries: 'Total Beneficiaries',
    totalDonations: 'Total Donations',
    totalEvents: 'Total Events',
    totalConvoys: 'Total Convoys',
    monthlyDonations: 'Monthly Donations',
    missionsByStatus: 'Missions by Status',
    regionalDistribution: 'Regional Distribution',
    recentDonations: 'Recent Donations',
    platformTitle: 'Humanitarian Platform Morocco',
    heroTitle: 'Together for a Solidarity Morocco',
    heroSubtitle: 'Intelligent management platform for humanitarian missions and volunteers in Morocco',
    getStarted: 'Get Started',
    learnMore: 'Learn More',
    forgotPassword: 'Forgot Password?',
    rememberMe: 'Remember Me',
    donationAmount: 'Donation Amount',
    paymentMethod: 'Payment Method',
    skills: 'Skills',
    available: 'Available',
    unavailable: 'Unavailable',
    familySize: 'Family Size',
    emergencyLevel: 'Emergency Level',
    departureCity: 'Departure City',
    destinationCity: 'Destination City',
    cargo: 'Cargo',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    critical: 'Critical',
    pending: 'Pending',
    inTransit: 'In Transit',
    delivered: 'Delivered',
    delayed: 'Delayed',
    upcoming: 'Upcoming',
    ongoing: 'Ongoing',
    allRegions: 'All Regions',
    allStatuses: 'All Statuses',
    filterByRegion: 'Filter by Region',
    filterByStatus: 'Filter by Status',
    exportPdf: 'Export PDF',
    details: 'Details',
    assignVolunteers: 'Assign Volunteers',
    close: 'Close'
  }
}

const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(localStorage.getItem('language') || 'fr')

  const changeLanguage = (lang) => {
    setLanguage(lang)
    localStorage.setItem('language', lang)
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr'
    document.documentElement.lang = lang
  }

  const t = (key) => {
    return translations[language]?.[key] || translations.fr[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
